-- ==============================================================================
-- Bharat Explore (SIH 2026) - Complete Supabase Cloud Schema & Migration
-- Paste and run this script in the Supabase Dashboard -> SQL Editor
-- ==============================================================================

-- 1. Enable UUID Extension
create extension if not exists "uuid-ossp";

-- 2. User Profiles Table (Synchronized with auth.users)
create table if not exists public.profiles (
    id uuid references auth.users on delete cascade primary key,
    email text,
    full_name text,
    phone text,
    avatar text default '🏔️',
    travel_style text default 'Eco-Explorer',
    home_city text,
    emergency_contact text,
    medical_notes text,
    preferences jsonb default '{"travel_style": "Eco-Explorer", "dietary": "Standard", "high_altitude_certified": false}'::jsonb,
    role text default 'traveler',
    is_active boolean default true,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

-- 3. Automatic Profile Creation Trigger on User Registration
create or replace function public.handle_new_user()
returns trigger as $$
begin
    insert into public.profiles (
        id,
        email,
        full_name,
        phone,
        avatar,
        travel_style,
        home_city,
        emergency_contact,
        medical_notes,
        preferences,
        role
    )
    values (
        new.id,
        new.email,
        coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
        coalesce(new.raw_user_meta_data->>'phone', ''),
        coalesce(new.raw_user_meta_data->>'avatar', '🏔️'),
        coalesce(new.raw_user_meta_data->>'travel_style', 'Eco-Explorer'),
        coalesce(new.raw_user_meta_data->>'home_city', ''),
        coalesce(new.raw_user_meta_data->>'emergency_contact', ''),
        coalesce(new.raw_user_meta_data->>'medical_notes', ''),
        coalesce(new.raw_user_meta_data->'preferences', '{"travel_style": "Eco-Explorer", "dietary": "Standard", "high_altitude_certified": false}'::jsonb),
        coalesce(new.raw_user_meta_data->>'role', 'traveler')
    )
    on conflict (id) do update set
        email = excluded.email,
        full_name = coalesce(excluded.full_name, public.profiles.full_name),
        updated_at = now();
    return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert on auth.users
    for each row execute function public.handle_new_user();

-- 4. Curated Destinations Dataset Table
create table if not exists public.destinations (
    id text primary key,
    name text not null,
    location text not null,
    state text not null,
    category text not null,
    emotion text,
    best_season text not null,
    difficulty text default 'Easy',
    type text not null,
    budget integer default 3000,
    img text not null,
    "desc" text not null,
    created_at timestamp with time zone default now()
);

-- 5. Real-Time Mountain Pass Advisories & Telemetry Table
create table if not exists public.pass_advisories (
    id text primary key,
    name text not null,
    status text not null,
    altitude text not null,
    condition text not null,
    safe boolean default true,
    temperature text default '-2°C',
    last_updated timestamp with time zone default now()
);

-- 6. Saved Journeys & Circuit Bookmarks Table
create table if not exists public.saved_journeys (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users on delete cascade,
    session_id text not null,
    destination_ids jsonb not null default '[]'::jsonb,
    notes text,
    travel_style text,
    created_at timestamp with time zone default now()
);

-- 7. Custom User Trip Expeditions Table
create table if not exists public.user_trips (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users on delete cascade,
    title text not null,
    destination_ids jsonb not null default '[]'::jsonb,
    start_date text,
    duration_days integer default 5,
    travel_style text default 'Eco-Explorer',
    notes text,
    created_at timestamp with time zone default now()
);

-- 8. Row Level Security (RLS) Configuration
alter table public.profiles enable row level security;
alter table public.destinations enable row level security;
alter table public.pass_advisories enable row level security;
alter table public.saved_journeys enable row level security;
alter table public.user_trips enable row level security;

-- RLS Policies
drop policy if exists "Public can read destinations" on public.destinations;
create policy "Public can read destinations" on public.destinations for select using (true);

drop policy if exists "Public can read passes" on public.pass_advisories;
create policy "Public can read passes" on public.pass_advisories for select using (true);

drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile" on public.profiles for select using (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

drop policy if exists "Public access to saved journeys" on public.saved_journeys;
create policy "Public access to saved journeys" on public.saved_journeys for all using (true);

drop policy if exists "Users can view own trips" on public.user_trips;
create policy "Users can view own trips" on public.user_trips for select using (auth.uid() = user_id);

drop policy if exists "Users can insert own trips" on public.user_trips;
create policy "Users can insert own trips" on public.user_trips for insert with check (auth.uid() = user_id);

drop policy if exists "Users can delete own trips" on public.user_trips;
create policy "Users can delete own trips" on public.user_trips for delete using (auth.uid() = user_id);

-- 9. Seed Curated Destinations
insert into public.destinations (id, name, location, state, category, emotion, best_season, difficulty, type, budget, img, "desc")
values
    ('pangong', 'Pangong Tso Lake', 'Ladakh', 'Ladakh', 'mountains', 'peace', 'May–Sep', 'Easy', 'Nature', 5000, 'https://images.unsplash.com/photo-1577500680965-6054e87d944b?auto=format&fit=crop&fm=jpg&q=85&w=1400', 'A dramatic 134 km saline lake at 14,270 ft that famously shifts from turquoise to azure.'),
    ('nubra', 'Nubra Valley', 'Ladakh', 'Ladakh', 'mountains', 'adventure', 'May–Sep', 'Moderate', 'Adventure', 6500, 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=900&q=85', 'High-altitude cold desert featuring silver sand dunes, Bactrian double-humped camels, and Diskit Gompa.'),
    ('khardung', 'Khardung La Pass', 'Ladakh', 'Ladakh', 'adventure', 'adventure', 'May–Oct', 'Moderate', 'Mountain', 2500, 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=900&q=85', 'Legendary Himalayan mountain pass at 17,582 ft connecting Leh to Nubra and Siachen glacier base.'),
    ('tsomoriri', 'Tso Moriri Lake', 'Ladakh', 'Ladakh', 'nature', 'peace', 'May–Sep', 'Moderate', 'Lake', 7000, 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=85', 'A serene Changthang high-altitude wetland sanctuary hosting black-necked cranes and Bar-headed geese.'),
    ('leh', 'Leh Historic Old Town', 'Ladakh', 'Ladakh', 'culture', 'culture', 'Apr–Oct', 'Easy', 'Culture', 3500, 'https://images.unsplash.com/photo-1533130061792-64b345e4a833?auto=format&fit=crop&w=900&q=85', 'The beating heart of Ladakh, home to Leh Palace, traditional clay ovens, local handicraft bazars, and bakeries.'),
    ('shanti', 'Shanti Stupa', 'Leh', 'Ladakh', 'spirituality', 'spirituality', 'Apr–Oct', 'Easy', 'Spiritual', 500, 'https://images.unsplash.com/photo-1657617832971-6e966739cd10?auto=format&fit=crop&fm=jpg&q=85&w=1400', 'A gleaming white-domed Buddhist stupa atop Chanspa hill offering panoramic 360° views of Leh valley and Zanskar ranges.'),
    ('hemis', 'Hemis Monastery', 'Ladakh', 'Ladakh', 'culture', 'culture', 'Jun–Sep', 'Easy', 'Heritage', 1200, 'https://images.unsplash.com/photo-1533130061792-64b345e4a833?auto=format&fit=crop&w=900&q=85', 'Drukpa lineage Buddhist monastery dating back to 1672, celebrated for sacred Cham masked dances and ancient murals.'),
    ('zanskar', 'Zanskar Valley', 'Ladakh', 'Ladakh', 'adventure', 'adventure', 'Jun–Sep', 'Hard', 'Adventure', 9000, 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=900&q=85', 'Raw, isolated Himalayan gorges, Phugtal cliffside cave monastery, and the famed winter Chadar trek route.'),
    ('spiti', 'Spiti Valley', 'Himachal Pradesh', 'Himachal Pradesh', 'mountains', 'adventure', 'Jun–Oct', 'Hard', 'Adventure', 8000, 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=900&q=85', 'Middle Land cold mountain desert valley preserving 1,000-year-old Key Monastery, fossil villages, and high passes.'),
    ('jaipur', 'Amber Fort & Pink City', 'Jaipur', 'Rajasthan', 'heritage', 'culture', 'Oct–Mar', 'Easy', 'Heritage', 4000, 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=900&q=85', 'Opulent Rajput hilltop palace fortification overlooking Maota Lake with Sheesh Mahal mirror mosaics.'),
    ('varanasi', 'Ganga Ghats & Kashi', 'Varanasi', 'Uttar Pradesh', 'spirituality', 'spirituality', 'Oct–Mar', 'Easy', 'Spiritual', 2500, 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=900&q=85', 'One of the world''s oldest living cities, spiritual dawn boat rides, sacred Dashashwamedh evening aarti on the holy Ganga.'),
    ('munnar', 'Munnar Tea Hills', 'Munnar', 'Kerala', 'nature', 'peace', 'Sep–May', 'Easy', 'Nature', 4500, 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=900&q=85', 'Endless rolling emerald tea plantations, mist-draped Western Ghat peaks, and Eravikulam Nilgiri Tahr sanctuary.')
on conflict (id) do nothing;

-- 10. Seed Mountain Pass Advisories
insert into public.pass_advisories (id, name, status, altitude, condition, safe, temperature, last_updated)
values
    ('khardung_la', 'Khardung La', 'OPEN', '17,582 ft', 'Pass is clear of fresh black ice. Snow chains mandatory for 2WD vehicles beyond South Pullu check post.', true, '-4°C', now()),
    ('chang_la', 'Chang La', 'CAUTION', '17,688 ft', 'Light snow flurry observed at summit. Army transit convoys priority between 09:00 - 11:00 AM.', true, '-7°C', now()),
    ('zoji_la', 'Zoji La', 'OPEN', '11,575 ft', 'Single-lane controlled convoy movement between Sonamarg and Drass. Clear visibility.', true, '2°C', now()),
    ('baralacha_la', 'Baralacha La', 'CAUTION', '15,910 ft', 'Sub-zero temperatures causing morning road freezing. Proceed in 4WD with cautious momentum.', true, '-6°C', now()),
    ('rohtang_la', 'Rohtang La', 'OPEN', '13,058 ft', 'Green transit corridor open with valid NGT tourist permit. Moderate mountain winds.', true, '1°C', now()),
    ('taglang_la', 'Taglang La', 'CAUTION', '17,480 ft', 'Second highest motorable pass on Manali-Leh road. Strong crosswinds; maintain lower gear descent.', true, '-3°C', now())
on conflict (id) do nothing;
